// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJRt0zEIfc985_-Vj5c41TF8QNsWnEj2g',
    appId: '1:525446782169:web:84402e0ef3c1ebebcc72c8',
    messagingSenderId: '525446782169',
    projectId: 'socialapp-69',
    authDomain: 'socialapp-69.firebaseapp.com',
    storageBucket: 'socialapp-69.firebasestorage.app',
    measurementId: 'G-RPS0XWCEYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-6eRvfy3qS0nFEtnxEvt25FoJhEXxBU8',
    appId: '1:525446782169:android:301d9ff70bdc0732cc72c8',
    messagingSenderId: '525446782169',
    projectId: 'socialapp-69',
    storageBucket: 'socialapp-69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxxTaYa00ZQ_x-j8BNFHE_BNaRoHQ-Ms4',
    appId: '1:525446782169:ios:2aec7cb33089e956cc72c8',
    messagingSenderId: '525446782169',
    projectId: 'socialapp-69',
    storageBucket: 'socialapp-69.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
